---
title: "MergeSEIFandImmunization"
author: "Alex Brooks"
date: "30/09/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(readxl)
library(dplyr)

```

```{r}
seifa <- read.csv("../raw_data/SEIFA_POA_15092018125111153.csv")
seifa_2016 <- read.csv("../raw_data/ABS_SEIFA2016_POA_26092018193603879.csv")
```

```{r}

seifa_old = seifa[,c(1,3,5,8,9)]

setDT(seifa_old)   # coerce to data.table

seifa_old_wide = dcast(seifa_old,
                    POA+Time~INDEX_TYPE+MEASURE,
                    value.var = c("Value"))

seifa_new = seifa_2016[,c(1,3,5,8,9)]

setDT(seifa_new)   # coerce to data.table

seifa_new_wide <- dcast(seifa_new,
                        POA+Time~SEIFAINDEXTYPE+SEIFA_MEASURE,
                        value.var = c("Value"))

```

```{r}
#Read immunisation data
immunisation <- read.csv("../cleaned_data/immunisation_data.csv")

immunisation$postcode <- as.factor(immunisation$postcode)


#We have two seifa files one for pre 2016 one for  2016 onwards which we will have to merge.
immunisation_2015 <- immunisation[immunisation$year <= 2015, ]
immunisation_2016 <- immunisation[immunisation$year > 2015, ]

```

```{r}

immunisation_seifa_2015 <- merge(immunisation_2015,seifa_old_wide,by.x='postcode',by.y='POA',how='left')

immunisation_seifa_2016 <- merge(immunisation_2016,seifa_new_wide,by.x='postcode',by.y='POA',how='left')

#setdiff(colnames(immunisation_seifa_2016),colnames(immunisation_seifa_2015))

all_immunisation_seifa <- rbind(immunisation_seifa_2016,immunisation_seifa_2015)

all_immunisation_seifa$electorate = NA

#Write this to a file
#write.csv(all_immunisation_seifa,"../cleaned_data/all_immunisation_seifa.csv", row.names=FALSE)

```

raw_data/electorates_by_postcode_2016.csv from
https://www.aph.gov.au/About_Parliament/Parliamentary_Departments/Parliamentary_Library/pubs/rp/rp0304/04rp11table2

```{r}


electorates <- read.csv("../raw_data/electorates_by_postcode_2016.csv")

colnames(electorates) <- c("postcode", "division", "percent")
electorates$division <- as.character(electorates$division)

  #For each row in immunisation data
  for(i in 1:nrow(all_immunisation_seifa)) {
    #Filter electorate records for rows with a corresponding postcode
    electorate_list = electorates %>%
      filter(postcode == all_immunisation_seifa$postcode[i]) %>%
      arrange(desc(percent))
    #Get the record with the highest ratio and add its electorate for the immunisation_data record
    all_immunisation_seifa$electorate[i] = electorate_list$division[1]
  }


write.csv(all_immunisation_seifa,"../cleaned_data/all_immunisation_seifa.csv", row.names=FALSE)
```

2016 SA3 data
```{r}

sa3_2016 <- read.csv("../raw_data/SA3_POA_2016.csv")
sa3_2011 <- read.csv("../raw_data/POA_SA3_2011.csv")
imm_data <- read.csv("../cleaned_data/all_immunisation_seifa.csv")

imm_data_2016 <- imm_data %>%
    filter(year == 2016)

imm_data_2011 <- imm_data %>%
    filter(year != 2016)

sa3_2016 <- sa3_2016 %>%
  select(SA3_CODE_2016, POA_CODE_2016)

sa3_2011 <- sa3_2011 %>%
  select(SA3_CODE_2011, POSTCODE_2011)

full_2016 <- merge(imm_data_2016,sa3_2016,by.x='postcode',by.y='POA_CODE_2016',how='left')

colnames(full_2016)[colnames(full_2016)=="SA3_CODE_2016"] <- "SA3_CODE"

full_2011 <- merge(imm_data_2011,sa3_2011,by.x='postcode',by.y='POSTCODE_2011',how='left')

colnames(full_2011)[colnames(full_2011)=="SA3_CODE_2011"] <- "SA3_CODE"

output <- rbind(full_2011, full_2016)

write.csv(output,"../cleaned_data/all_immunisation_seifa.csv", row.names=FALSE)
```


